// ============================================================
// CORE DATA TYPES — Customer Voice Mirror
// ============================================================
// Two namespaces:
//   - DB types (persisted, have id from Prisma cuid())
//   - DTO types (in-memory, may not be persisted)
// Agents work with DTOs internally; persistence is handled by orchestrator.
// ============================================================

// ---------- IDS ----------
// All IDs are strings (cuid). Generation rules:
//   - Run.id: generated by API route on POST /api/analyze
//   - Source.id: generated on persistence (NOT by scraper)
//   - Theme.id, Memo.id: generated on persistence
// In-memory DTOs from scrapers use a temporaryRef field instead.

// ---------- RUN ----------
export type RunStatus =
  | 'PENDING' | 'SCRAPING' | 'EXTRACTING'
  | 'SYNTHESIZING' | 'RENDERING' | 'COMPLETE' | 'FAILED';

export interface Run {
  id: string;
  url: string;
  companyName: string | null;
  companyDomain: string;
  status: RunStatus;
  createdAt: Date;
  completedAt: Date | null;
  error: string | null;
  promptVersion: string;
  totalCostUsd: number;
  totalLatencyMs: number;
  demoSlug?: string | null;
}

// ---------- SOURCES ----------
export type SourceType =
  | 'CUSTOMER_STORY' | 'REDDIT_POST' | 'REDDIT_COMMENT'
  | 'X_MENTION' | 'TRUSTPILOT_REVIEW' | 'OTHER_REVIEW'
  | 'THIRD_PARTY_REVIEW';

export type SourceReliability = 'HIGH' | 'MEDIUM' | 'LOW';

export type SourceMetadata =
  | { type: 'CUSTOMER_STORY'; storySlug: string; customerCompany: string | null; customerRole: string | null }
  | { type: 'REDDIT_POST'; subreddit: string; upvotes: number; numComments: number }
  | { type: 'REDDIT_COMMENT'; subreddit: string; postUrl: string; upvotes: number }
  | { type: 'X_MENTION'; followers: number | null; isReply: boolean }
  | { type: 'TRUSTPILOT_REVIEW'; rating: number; verified: boolean }
  | { type: 'OTHER_REVIEW'; platform: string; rating: number | null }
  | { type: 'THIRD_PARTY_REVIEW'; reviewerName: string; reviewerUrl: string };

export interface SourceDTO {
  temporaryRef: string;
  type: SourceType;
  url: string;
  title: string | null;
  author: string | null;
  authorContext: string | null;
  publishedAt: Date | null;
  rawText: string;
  reliability: SourceReliability;
  metadata: SourceMetadata;
}

export interface Source extends Omit<SourceDTO, 'temporaryRef'> {
  id: string;
  runId: string;
  capturedAt: Date;
}

// ---------- THEMES ----------
export type ThemeCategory =
  | 'JOB_TO_BE_DONE' | 'LOVE' | 'FRUSTRATION'
  | 'WISH' | 'CHURN_RISK' | 'COMPETITIVE_REFERENCE'
  | 'CONTRADICTION';

export interface VerbatimQuoteDTO {
  text: string;
  sourceTemporaryRef: string;
  sourceUrl: string;
  sourceReliability: SourceReliability;
}

export interface VerbatimQuote {
  id: string;
  text: string;
  sourceId: string;
  sourceUrl: string;
  sourceReliability: SourceReliability;
  themeId: string;
}

export interface ThemeDTO {
  category: ThemeCategory;
  statement: string;
  verbatimQuotes: VerbatimQuoteDTO[];
  sourceCount: number;
  weightedConfidence: number;
}

export interface Theme extends Omit<ThemeDTO, 'verbatimQuotes'> {
  id: string;
  runId: string;
  verbatimQuotes: VerbatimQuote[];
}

// ---------- MEMO ----------
export type CoverageGrade = 'STRONG' | 'MODERATE' | 'THIN';

export const COVERAGE_THRESHOLDS = {
  STRONG: { totalSources: 25, customerStories: 3, externalSources: 15 },
  MODERATE: { totalSources: 15, customerStories: 1, externalSources: 8 },
} as const;

export interface MemoSection {
  themes: ThemeDTO[];
  summary: string;
}

export interface MemoDTO {
  companyName: string;
  generatedAt: Date;
  promptVersion: string;

  jobToBeDone: {
    statement: string;
    rationale: string;
    supportingQuotes: VerbatimQuoteDTO[];
  };

  whatTheyLove: MemoSection;
  whatFrustrates: MemoSection;
  whatTheyWish: MemoSection;
  contradictions: MemoSection;

  dominantPattern: {
    statement: string;
    elaboration: string;
    falsifiability: string;
    falsifiabilityCheck: 'SPECIFIC' | 'GENERIC';
  };

  sourceCoverage: {
    totalSources: number;
    customerStories: number;
    redditPosts: number;
    xMentions: number;
    reviews: number;
    coverageGrade: CoverageGrade;
    limitations: string[];
  };

  renderedMarkdown: string;
}

export interface Memo extends Omit<MemoDTO, never> {
  id: string;
  runId: string;
}

// ---------- AGENT EXECUTION ----------
export type AgentName = 'SCRAPER' | 'EXTRACTOR' | 'SYNTHESIZER' | 'RENDERER';
export type AgentState = 'PENDING' | 'RUNNING' | 'COMPLETE' | 'FAILED' | 'SKIPPED';

export interface AgentRun {
  id: string;
  runId: string;
  agentName: AgentName;
  state: AgentState;
  message: string;
  progress: number | null;
  startedAt: Date | null;
  completedAt: Date | null;
  costUsd: number;
  latencyMs: number;
  errorDetail: string | null;
  inputHash: string | null;
  outputRef: string | null;
}

// ---------- COVERAGE GRADING ----------
export function gradeCoverage(coverage: {
  totalSources: number;
  customerStories: number;
  externalSources: number;
}): CoverageGrade {
  const { totalSources, customerStories, externalSources } = coverage;
  const strong = COVERAGE_THRESHOLDS.STRONG;
  const moderate = COVERAGE_THRESHOLDS.MODERATE;

  if (
    totalSources >= strong.totalSources &&
    customerStories >= strong.customerStories &&
    externalSources >= strong.externalSources
  ) return 'STRONG';

  if (
    totalSources >= moderate.totalSources &&
    customerStories >= moderate.customerStories &&
    externalSources >= moderate.externalSources
  ) return 'MODERATE';

  return 'THIN';
}

// ---------- RELIABILITY WEIGHTING ----------
export const RELIABILITY_WEIGHTS = {
  HIGH: 1.0,
  MEDIUM: 0.7,
  LOW: 0.4,
} as const;

export function computeWeightedConfidence(
  quotes: { sourceReliability: SourceReliability }[]
): number {
  if (quotes.length === 0) return 0;
  const sum = quotes.reduce(
    (acc: number, q) => acc + RELIABILITY_WEIGHTS[q.sourceReliability],
    0,
  );
  return sum / quotes.length;
}